### ISSUE TITLE
problem with SubscribeToNextGroupMessage

### ISSUE THREAD

**Issue by scanner69** [dewwalters/Wolf.Net#5]
dim rid as integer = 1234
Dim req As Message = Await control.SubscribeToNextGroupMessage(rid)

not working or getting the messages

**Comment by scanner69** [comment]
1234 is example of my group id

**Comment by scanner69** [comment]
this code is c# and not work

 public async Task LoginControlAsync()
        {
            Wolf.Net.WolfBot abc = new Wolf.Net.WolfBot();
          await  abc.LoginAsync("example@hotmail.com", "1111");
            Message req = await abc.SubscribeToNextGroupMessage(1234);
            MessageBox.Show(req.Content);
        }

**Comment by scanner69** [comment]
@dewwalters

**Comment by dewwalters** [comment]
Install-Package Wolf.Net -Version 2.1.5
